"""
email_utils.py
Sends the MediPredict AI risk report (HTML email + PDF attachment)
via SMTP. Configure credentials with environment variables so you
never hard-code your email password in source control:

    MAIL_SERVER    e.g. smtp.gmail.com
    MAIL_PORT      e.g. 587
    MAIL_USERNAME  your sending email address
    MAIL_PASSWORD  an app password (NOT your normal account password)
    MAIL_SENDER    "MediPredict AI <your_email@gmail.com>"  (optional, defaults to MAIL_USERNAME)

For Gmail: enable 2-Step Verification on the account, then create an
"App Password" (Google Account -> Security -> App Passwords) and use
that 16-character value as MAIL_PASSWORD.
"""

import os
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.application import MIMEApplication

MAIL_SERVER = os.environ.get("MAIL_SERVER", "smtp.gmail.com")
MAIL_PORT = int(os.environ.get("MAIL_PORT", "587"))
MAIL_USERNAME = os.environ.get("MAIL_USERNAME")
MAIL_PASSWORD = os.environ.get("MAIL_PASSWORD")
MAIL_SENDER = os.environ.get("MAIL_SENDER", MAIL_USERNAME)


def is_mail_configured():
    return bool(MAIL_USERNAME and MAIL_PASSWORD)


def send_report_email(to_email, patient_name, disease_summary_html, pdf_bytes, pdf_filename="MediPredict_Report.pdf"):
    """
    to_email: recipient email address (patient's stored email)
    patient_name: used in the greeting
    disease_summary_html: small HTML snippet listing disease(s) & score(s)
    pdf_bytes: BytesIO or bytes of the generated PDF report
    """
    if not is_mail_configured():
        raise RuntimeError(
            "Email is not configured. Set MAIL_USERNAME and MAIL_PASSWORD "
            "environment variables (see email_utils.py docstring)."
        )

    msg = MIMEMultipart("mixed")
    msg["Subject"] = "Your MediPredict AI Risk Report"
    msg["From"] = MAIL_SENDER
    msg["To"] = to_email

    html_body = f"""
    <div style="font-family:Arial,sans-serif;max-width:560px;margin:0 auto;color:#0e0e0e;">
      <div style="background:#e8392a;padding:20px 28px;border-radius:10px 10px 0 0;">
        <h2 style="color:#fff;margin:0;font-size:18px;">MediPredict AI</h2>
      </div>
      <div style="border:1px solid #e5e3dd;border-top:none;padding:28px;border-radius:0 0 10px 10px;">
        <p>Hi {patient_name or 'there'},</p>
        <p>Your disease risk prediction report is ready. A summary is below, and the
        full report is attached as a PDF.</p>
        {disease_summary_html}
        <p style="margin-top:20px;font-size:13px;color:#6b6b6b;">
          ⚠️ This is generated by a machine learning model and is for informational
          purposes only. It is not a medical diagnosis. Please consult a qualified
          healthcare professional.
        </p>
        <p style="margin-top:24px;">— MediPredict AI Team</p>
      </div>
    </div>
    """
    msg.attach(MIMEText(html_body, "html"))

    pdf_part = MIMEApplication(
        pdf_bytes.read() if hasattr(pdf_bytes, "read") else pdf_bytes,
        Name=pdf_filename,
    )
    pdf_part["Content-Disposition"] = f'attachment; filename="{pdf_filename}"'
    msg.attach(pdf_part)

    with smtplib.SMTP(MAIL_SERVER, MAIL_PORT) as server:
        server.starttls()
        server.login(MAIL_USERNAME, MAIL_PASSWORD)
        server.sendmail(MAIL_SENDER, [to_email], msg.as_string())